"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.hexColorSixDigit = exports.hexColor = exports.commentSentId = exports.commentLabel = exports.fallback = exports.sdDependencyNoWhitespace = exports.sdDependency = exports.whiteline = exports.whitespaceLine = exports.whitespace = exports.cg3Other = exports.cg3Deprel = exports.cg3Index = exports.cg3Head = exports.cg3Dependency = exports.cg3TokenContent = exports.cg3TokenStart = exports.conlluEmptyIndex = exports.conlluTokenLineTenParams = exports.conlluTokenLine = exports.comment = exports.spaceBeforePunctuation = exports.sentenceThenPunctuation = exports.allPunctuation = exports.punctuation = exports.multiNewlines = void 0;
exports.multiNewlines = /\n{2,}/g;
exports.punctuation = /[.,!?;]+/g;
exports.allPunctuation = /^[.,!?;]+$/;
exports.sentenceThenPunctuation = /([^.!?]*[.!?]*)/g;
exports.spaceBeforePunctuation = /\s+([.,!?;]+)/g;
exports.comment = /^(#\s*(.*))(\n|$)/;
exports.conlluTokenLine = /^((\d+(\.\d+)?)(\-(\d+(\.\d+)?))?)(.+)/;
exports.conlluTokenLineTenParams = /^((\d+(\.\d+)?)(\-(\d+(\.\d+)?))?)((\s+\S+){8,9})/;
exports.conlluEmptyIndex = /^(\d+)(\.\d+)?/;
exports.cg3TokenStart = /^["']<((.|\\")*)>["']/;
exports.cg3TokenContent = /^(;?)(\s+)"((.|\\")*)"(([ \t]+\S+)*)/;
exports.cg3Dependency = /#?\d+(->\d*)?$/;
exports.cg3Head = /#\d+->(\d*)$/;
exports.cg3Index = /#(\d+)/;
exports.cg3Deprel = /\s@([\w=]*)/;
exports.cg3Other = /([^;].*(=.+)?)/;
exports.whitespace = /(\s+)/;
exports.whitespaceLine = /^(\s*)$/;
exports.whiteline = /^(\s*)(\n|$)/;
exports.sdDependency = /^\s*([\w.]+)\(([\w.]+),\s*([\w.]+)\)\s*$/;
exports.sdDependencyNoWhitespace = /^([\w.]+)\(([\w.]+),\s*([\w.]+)\)$/;
exports.fallback = /^_$/;
exports.commentLabel = /(\s*)(labels?|tags?)\s*=\s*(\w.*)/;
exports.commentSentId = /(\s*)sent.?id\s*=\s*(\w*)/i;
exports.hexColor = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i;
exports.hexColorSixDigit = /^#?([a-f\d]{6})/i;
//# sourceMappingURL=regex.js.map